### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by sindresorhus** [lucaperret/kap-now#2]
Nice work on this plugin! Glad to see more Kap plugins in the ecosystem.

Some quick feedback:

- This can be removed: https://github.com/lucaperret/kap-now/blob/94ced5120c008f8e12d1d3303165f36259f3df20/index.js#L11 Kap already sets progress for converting the file and reading it doesn't take long.
- This seems inefficient: https://github.com/lucaperret/kap-now/blob/94ced5120c008f8e12d1d3303165f36259f3df20/index.js#L13-L17 Both `crypto` and the endpoint supports a stream, so you can just use a stream the whole way, using `fs.createReadStream`.
- https://github.com/lucaperret/kap-now/blob/94ced5120c008f8e12d1d3303165f36259f3df20/index.js#L50 It's not always a `video`. It can be a GIF or APNG too. You can use `context.format` for now and `.toUpperCase()` it. I'll add a new method later to get the pretty name: https://github.com/wulkano/kap/pull/389

**Comment by sindresorhus** [comment]
Hmm, I just noticed https://github.com/lucaperret/kap-now/blob/94ced5120c008f8e12d1d3303165f36259f3df20/index.js#L23 It seems weird of Now to require the SHA up front. That means you can't stream files directly from the filesystem. Are you sure this is required?

**Comment by matheuss** [comment]
@sindresorhus yeah, the SHA is necessary upfront. You can stream, but not from an _unknown_ stream. 

Related: https://github.com/lucaperret/kap-now/issues/3

**Comment by lucaperret** [comment]
Thanks for your feedback, I'm novice using stream...
```javascript
const file = createReadStream(await context.filePath());
const hash = createHash('sha1').setEncoding('hex');
file.pipe(hash);
// set the file length variable
// set the sha variable from `hash` stream
```
I should retrieve the file length and sha to send as headers to now, 
Should I use the `finish` event for the sha ? and the `getStream` utility to have the length of the file ?

**Comment by sindresorhus** [comment]
You don’t have to read in the file for the size. Just `fs.stat` it.

**Comment by lucaperret** [comment]
ok, got it.
But for the hash, I'm doing like that:
```javascript
const filePath = await context.filePath();
const file = createReadStream(filePath);
const fileLength = statSync(filePath).size;
const hash = createHash('sha1').setEncoding('hex');
file.pipe(hash);
await pEvent(hash, 'finish');
const sha = hash.read();
```
Is that the good way ? 🤕

**Comment by lucaperret** [comment]
Or using the https://github.com/sindresorhus/hasha library ?

**Comment by sindresorhus** [comment]
Yeah, you could use https://github.com/sindresorhus/hasha#hashafromstreamstream-options

**Comment by lucaperret** [comment]
Ok I'm using it now.
When posting the stream, got catch a socket hang up. Is it because the Now endpoint doesn't support read stream ?
```javascript
await context.request(nowBaseUrl + 'files', {
	headers: {
		'Content-Type': 'application/octet-stream',
		'x-now-digest': sha,
		'Content-Length': fileLength,
		'x-now-size': fileLength,
		Authorization
	},
	body: fs.createReadStream(filePath)
});
```

**Comment by lucaperret** [comment]
It seems that streams aren't yet supported by Now, right @matheuss ?

**Comment by lucaperret** [comment]
Hi @sindresorhus, it seems that the sha should be passed on headers...
