### ISSUE TITLE
Error after upload

### ISSUE THREAD

**Issue by adamyonk** [lucaperret/kap-now#4]
Getting this error after trying to upload a gif:
![image](https://user-images.githubusercontent.com/33258/35998499-6f7fe8d6-0ce2-11e8-812d-9fb97b180dce.png)

**Comment by lucaperret** [comment]
You should configure your [Now token](https://zeit.co/account/tokens), in the plugin configuration.
Go to the Plugins tab of the Kap Preferences, Open plugins folder, edit the kap-now.json file and add a `token` property with your token. I've added this in the documentation:  32557fdf90447db8d70a856f467f45699538955b

**Comment by adamyonk** [comment]
Thanks, @lucaperret!
